easy_admin:
    site_name: 'Montessori Ressources'
    design:
      menu:
        - { label: 'Admin' }
        - { entity: 'User', icon: 'user' }
        - { label: 'Content' }
        - { entity: 'Card', icon: 'square' }
        - { entity: 'Image', icon: 'image' }
        - { label: 'Links' }
        - { label: 'Home', route: 'home', icon: 'home' }
    entities:
      Image:
        class: App\Entity\Image
        # ...
        list:
          fields:
            - { property: 'name', type: 'image', base_path: '%app.path.images%' }
            - label
        # ...
        show:
          fields:
            - { property: 'name', type: 'image', base_path: '%app.path.images%' }
            - label
        form:
          fields:
            - { property: 'file', type: 'vich_image' }
            - label

      Card:
        class: App\Entity\ClassifiedCard
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
      User:
        class: App\Entity\User
        list:
          fields:
            - username
            - email
            - enabled
            - lastLogin
